# Copyright © 2026 AtomGradient
# 版权所有 © 2026 质子梯度（北京）科技有限公司

"""EdgeKit project code generator.

Generates a Swift CLI project that uses EdgeKit to run an optimized model,
displaying tok/s and Edge Studio optimization metadata.
"""

from __future__ import annotations

import json
import os


def _load_config(model_dir: str) -> dict:
    config_path = os.path.join(model_dir, "config.json")
    if not os.path.exists(config_path):
        return {}
    with open(config_path) as f:
        return json.load(f)


def _build_optimization_summary(cfg: dict) -> tuple[list[str], bool]:
    """Return (summary_lines, is_optimized)."""
    lines = []

    vocab_pruning = cfg.get("vocab_pruning")
    if vocab_pruning:
        orig = vocab_pruning.get("original_vocab_size") or vocab_pruning.get("original_text_vocab_size")
        pruned = vocab_pruning.get("compact_vocab_size")  # correct key (not pruned_vocab_size)
        if orig and pruned:
            lines.append(f"vocab pruning: {orig} → {pruned} tokens")

    per_layer = cfg.get("per_layer_intermediate_sizes")
    if per_layer and isinstance(per_layer, list):
        std_size = cfg.get("intermediate_size") or cfg.get("text_config", {}).get("intermediate_size")
        pruned_count = sum(1 for s in per_layer if std_size and s < std_size) if std_size else 0
        lines.append(f"neuron pruning: {pruned_count}/{len(per_layer)} layers optimized")

    layer_pruning = cfg.get("text_layer_pruning")
    if layer_pruning and isinstance(layer_pruning, list):
        lines.append(f"layer pruning: {len(layer_pruning)} layers removed")

    weight_split = cfg.get("weight_split")
    if weight_split:
        lines.append("weight split: enabled")

    is_optimized = len(lines) > 0
    return lines, is_optimized


def _make_package_swift(edge_kit_path: str) -> str:
    return f'''// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "EdgeKitDemo",
    platforms: [.macOS(.v14)],
    dependencies: [
        // Local edge-kit checkout (development)
        .package(path: "{edge_kit_path}"),
        // GitHub:
        // .package(url: "https://github.com/AtomGradient/edge-kit.git", from: "1.0.0"),
    ],
    targets: [
        .executableTarget(
            name: "EdgeKitDemo",
            dependencies: [
                .product(name: "EdgeInference", package: "edge-kit"),
            ]
        ),
    ]
)
'''


def _make_main_swift(
    model_dir: str,
    model_name: str,
    opt_summary_lines: list[str],
    is_optimized: bool,
    cfg: dict,
) -> str:
    return f'''import EdgeInference
import Foundation

// ─────────────────────────────────────────────
//  EdgeKit Demo — generated by Edge Studio
//  Model: {model_name}
//  {'Optimized model (Edge Studio)' if is_optimized else 'Standard model'}
// ─────────────────────────────────────────────

let modelDir = "{model_dir}"
let prompt   = "What is machine learning? Explain briefly."
let maxTokens = 512

// @MainActor runs on DispatchQueue.main — use RunLoop.main.run() to keep
// the main thread alive and processing tasks (sema.wait() would deadlock).
Task {{ @MainActor in
    let engine = LLMEngine()

    do {{
        print("[EdgeKit] Loading model from: \\(modelDir)")
        try await engine.loadLocal(directory: URL(fileURLWithPath: modelDir))
        print("[EdgeKit] Model loaded ✓")
        print("")

        // Show Edge Studio optimizations detected at runtime from config.json
        if let meta = engine.pruningMetadata, meta.isEdgeOptimized {{
            print("[Edge Studio Optimizations]")
            print(meta.description)
            print("")
        }}

        print("Prompt: \\(prompt)")
        print("─────────────────────────────────────────────")

        var tokenCount = 0
        let startTime = Date()
        var firstToken = true
        let parameters = EdgeGenerateParameters(maxTokens: maxTokens)

        for try await chunk in engine.generateStream(messages: [.user(prompt)], parameters: parameters) {{
            if firstToken {{
                let ttft = Date().timeIntervalSince(startTime)
                print("[TTFT: \\(String(format: "%.3f", ttft))s]", terminator: " ")
                firstToken = false
            }}
            print(chunk.text, terminator: "")
            fflush(stdout)
            tokenCount += 1
        }}

        let elapsed = Date().timeIntervalSince(startTime)
        let toksPerSec = Double(tokenCount) / max(elapsed, 0.001)

        print("\\n")
        print("─────────────────────────────────────────────")
        print("[Stats] \\(tokenCount) tokens in \\(String(format: "%.2f", elapsed))s")
        print("[Stats] \\(String(format: "%.1f", toksPerSec)) tok/s")

        engine.unload()

    }} catch {{
        print("[Error] \\(error)")
        exit(1)
    }}

    exit(0)
}}

// Keep main thread alive so @MainActor tasks can execute
RunLoop.main.run()
'''


def _make_readme(model_name: str, model_dir: str, run_command: str, opt_lines: list[str]) -> str:
    opt_section = ""
    if opt_lines:
        bullet_list = "\n".join(f"- {line}" for line in opt_lines)
        opt_section = f"""
## Edge Studio Optimizations Applied

{bullet_list}

"""

    return f"""# EdgeKit Demo — {model_name}

Generated by **Edge Studio** .
{opt_section}
## Quick Start

```bash
mkdir EdgeKitDemo && cd EdgeKitDemo
# Copy Package.swift and Sources/main.swift here, then:
mkdir -p Sources/EdgeKitDemo
{run_command}
```

## What This Does

1. Loads `{model_dir}` via EdgeKit
2. Streams token generation with timing
3. Reports tok/s at completion

## Model Path

```
{model_dir}
```

## Integration into Your App

After verifying performance, integrate EdgeKit into your iOS/macOS app:

```swift
import EdgeInference

let engine = LLMEngine()
try await engine.loadLocal(directory: URL(fileURLWithPath: "path/to/model"))
let parameters = EdgeGenerateParameters(maxTokens: 512)
for try await chunk in engine.generateStream(messages: [.user("Hello")], parameters: parameters) {{
    print(chunk.text, terminator: "")
}}
engine.unload()
```
"""


_DEFAULT_EDGE_KIT_PATH = os.environ.get(
    "EDGE_KIT_PATH",
    os.path.expanduser("~/Documents/Codes/EdgeStudio/edge-kit"),
)


def generate_edge_runtime_project(
    model_dir: str,
    optimized_dir: str = "",
    edge_kit_path: str = _DEFAULT_EDGE_KIT_PATH,
) -> dict:
    """Generate EdgeKit Swift CLI project files.

    Returns dict with keys: package_swift, main_swift, readme, run_command,
    model_name, is_optimized, optimization_summary.
    """
    target_dir = optimized_dir.strip() if optimized_dir and optimized_dir.strip() else model_dir
    cfg = _load_config(target_dir)

    # Derive model name from directory
    model_name = os.path.basename(target_dir.rstrip("/"))

    # Build optimization summary
    opt_lines, is_optimized = _build_optimization_summary(cfg)
    opt_summary = "; ".join(opt_lines) if opt_lines else ""

    # Override edge_kit_path from env if set
    env_path = os.environ.get("EDGE_KIT_PATH", "").strip()
    if env_path:
        edge_kit_path = env_path

    package_swift = _make_package_swift(edge_kit_path)
    main_swift = _make_main_swift(target_dir, model_name, opt_lines, is_optimized, cfg)
    run_command = "swift run"
    readme = _make_readme(model_name, target_dir, run_command, opt_lines)

    return {
        "package_swift": package_swift,
        "main_swift": main_swift,
        "readme": readme,
        "run_command": run_command,
        "model_name": model_name,
        "is_optimized": is_optimized,
        "optimization_summary": opt_summary,
    }
