# Copyright © 2026 AtomGradient
# 版权所有 © 2026 质子梯度（北京）科技有限公司

"""Swift code generator — template-based Swift inference code for CoreML models.

Generates ready-to-use Swift code for loading and running inference with
exported CoreML models on iOS/macOS.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def generate_swift_code(
    model_dir: str,
    model_package_name: str = "Model",
    max_tokens: int = 256,
) -> str:
    """Generate Swift inference code for a CoreML model.

    Args:
        model_dir: path to original MLX model (for config extraction)
        model_package_name: name of the .mlpackage file (without extension)
        max_tokens: default max tokens for generation

    Returns:
        Complete Swift source code as a string.
    """
    config_path = Path(model_dir) / "config.json"
    config: dict[str, Any] = {}
    if config_path.exists():
        with open(config_path) as f:
            config = json.load(f)

    vocab_size = config.get("vocab_size", 32000)
    hidden_size = config.get("hidden_size", 4096)
    num_layers = config.get("num_hidden_layers", 32)
    model_type = config.get("model_type", "unknown")
    arch_name = config.get("architectures", ["LLM"])[0]

    return _SWIFT_TEMPLATE.format(
        model_package_name=model_package_name,
        vocab_size=vocab_size,
        hidden_size=hidden_size,
        num_layers=num_layers,
        max_tokens=max_tokens,
        model_type=model_type,
        arch_name=arch_name,
    )


_SWIFT_TEMPLATE = """\
//
// LLMInference.swift
// Generated by Edge Studio
//
// Model: {arch_name} ({model_type})
// Config: vocab_size={vocab_size}, hidden_size={hidden_size}, num_layers={num_layers}
//

import CoreML
import Foundation

/// LLM inference wrapper for CoreML model.
///
/// Usage:
/// ```swift
/// let llm = try LLMInference(modelName: "{model_package_name}")
/// let response = try await llm.generate(prompt: "Hello!", maxTokens: {max_tokens})
/// print(response)
/// ```
class LLMInference {{

    private let model: MLModel
    private let vocabSize: Int = {vocab_size}
    private let maxTokens: Int = {max_tokens}

    /// Initialize with a CoreML model.
    /// - Parameter modelName: Name of the .mlpackage (without extension)
    init(modelName: String = "{model_package_name}") throws {{
        let config = MLModelConfiguration()
        config.computeUnits = .all

        guard let modelURL = Bundle.main.url(
            forResource: modelName, withExtension: "mlpackage"
        ) else {{
            throw LLMError.modelNotFound(modelName)
        }}

        self.model = try MLModel(contentsOf: modelURL, configuration: config)
    }}

    /// Generate text from a prompt.
    /// - Parameters:
    ///   - prompt: Input text
    ///   - maxTokens: Maximum tokens to generate
    /// - Returns: Generated text
    func generate(prompt: String, maxTokens: Int? = nil) async throws -> String {{
        let limit = maxTokens ?? self.maxTokens
        let tokenIds = tokenize(prompt)
        var generatedIds: [Int] = []

        var currentInput = tokenIds
        for _ in 0..<limit {{
            let logits = try predict(inputIds: currentInput)
            let nextToken = sampleToken(logits: logits)

            if isEOS(nextToken) {{
                break
            }}

            generatedIds.append(nextToken)
            currentInput = [nextToken]
        }}

        return detokenize(generatedIds)
    }}

    // MARK: - Private

    private func predict(inputIds: [Int]) throws -> [Float] {{
        let inputArray = try MLMultiArray(shape: [1, NSNumber(value: inputIds.count)], dataType: .int32)
        for (i, id) in inputIds.enumerated() {{
            inputArray[i] = NSNumber(value: id)
        }}

        let input = try MLDictionaryFeatureProvider(dictionary: ["input_ids": inputArray])
        let output = try model.prediction(from: input)

        // Extract logits from output
        guard let logitsArray = output.featureValue(for: "output")?.multiArrayValue else {{
            throw LLMError.invalidOutput
        }}

        // Get last token's logits
        let seqLen = inputIds.count
        var logits = [Float](repeating: 0, count: vocabSize)
        for i in 0..<vocabSize {{
            logits[i] = logitsArray[(seqLen - 1) * vocabSize + i].floatValue
        }}

        return logits
    }}

    private func sampleToken(logits: [Float], temperature: Float = 0.7) -> Int {{
        if temperature == 0 {{
            // Greedy
            return logits.enumerated().max(by: {{ $0.element < $1.element }})?.offset ?? 0
        }}

        // Temperature scaling + softmax
        let scaled = logits.map {{ $0 / temperature }}
        let maxLogit = scaled.max() ?? 0
        let exps = scaled.map {{ exp($0 - maxLogit) }}
        let sumExps = exps.reduce(0, +)
        let probs = exps.map {{ $0 / sumExps }}

        // Sample from distribution
        let r = Float.random(in: 0..<1)
        var cumulative: Float = 0
        for (i, p) in probs.enumerated() {{
            cumulative += p
            if cumulative >= r {{
                return i
            }}
        }}
        return probs.count - 1
    }}

    private func tokenize(_ text: String) -> [Int] {{
        // TODO: Implement proper tokenization
        // For production, use a Swift tokenizer (e.g., swift-tokenizers)
        // This is a placeholder that returns dummy token IDs
        return Array(text.utf8).map {{ Int($0) }}
    }}

    private func detokenize(_ tokenIds: [Int]) -> String {{
        // TODO: Implement proper detokenization
        // For production, use a Swift tokenizer
        return String(tokenIds.compactMap {{ UnicodeScalar($0) }}.map {{ Character($0) }})
    }}

    private func isEOS(_ tokenId: Int) -> Bool {{
        // Common EOS token IDs — adjust for your model
        return tokenId == 2 || tokenId == 151645 || tokenId == 151643
    }}
}}

// MARK: - Errors

enum LLMError: LocalizedError {{
    case modelNotFound(String)
    case invalidOutput

    var errorDescription: String? {{
        switch self {{
        case .modelNotFound(let name):
            return "CoreML model '\\(name).mlpackage' not found in bundle"
        case .invalidOutput:
            return "Model output does not contain expected logits"
        }}
    }}
}}
"""
